[package]
name = "chave/private-physics"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact-hooks = "chipioindustries/roact-hooks@0.6.1"
roact = "roblox/roact@1.4.4"
comm = "sleitnick/comm@0.3.1"
signal = "sleitnick/signal@1.5.0"
sift = "csqrl/sift@0.0.6"
timer = "sleitnick/timer@1.1.2"
roact-spring = "chriscerie/roact-spring@1.1.6"
trove = "sleitnick/trove@0.5.0"
profileservice = "surnautica/profileservice@1.0.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"
promise = "evaera/promise@4.0.0"