[package]
name = "chipioindustries/roact-hooks"
description = "An implementation of hooks in Roact"
version = "0.6.1"
license = "MPL-2.0"
authors = ["Kampfkarren", "ChipioIndustries"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["wally.exe", "aftman", "*.zip"]
